id: aoanet
start_from: log/log_aoanet_coco

caption_model: aoa
refine: 1
refine_aoa: 1
use_ff: 0
num_heads: 8
mean_feats: 1
ctx_drop: 1
dropout_aoa: 0.3
input_json: data/cocotalk.json
input_label_h5: data/cocotalk_label.h5
input_fc_dir: data/cocobu_fc
input_att_dir: data/cocobu_att
input_box_dir: data/cocobu_box
seq_per_img: 5
batch_size: 10
beam_size: 1
num_layers: 2
input_encoding_size: 1024
rnn_size: 1024
language_eval: 1
val_images_use: -1
save_checkpoint_every: 3000
checkpoint_path: log/log_aoanet_coco_rl
max_epochs: 80
self_critical_after: 0
learning_rate_decay_start: -1
scheduled_sampling_start: -1
sample_n: 5
learning_rate: 0.00002
